### ISSUE TITLE
Unable to complete oAuth

### ISSUE THREAD

**Issue by mukowman** [emansih/FireflyMobile#2]
Unable to get oAuth completed.
Tried using external URL of FireFly which is behind a reverse proxy using SSL but unable to get past the "Authorize" prompt (nothing happens).
When I tried on my internal network when clicking the Authorize button it prompts me to open in FireFly mobile or Chrome. If i choose FireFly mobile i just get prompted with the login screen again but all fields are blank.

P.S. To confirm I was able to complete oAuth internally with the other Android client, but not externally.

**Comment by emansih** [comment]
> Tried using external URL of FireFly which is behind a reverse proxy using SSL but unable to get past the "Authorize" prompt (nothing happens).

What's your redirect URL? Is it `http://empty` ?

> all fields are blank.
Yea...regarding this... it's how android works by opening  a new activity instead of resuming the old activity upon receiving an intent from the browser. I will look into this issue. I might have some ideas on implementing a fix(or a hack, heh :grinning:)

**Comment by mukowman** [comment]
Tried both http://empty and https://empty
