### ISSUE TITLE
OAuth Login - CLEARTEXT communication not permitted

### ISSUE THREAD

**Issue by 8bitgentleman** [emansih/FireflyMobile#25]
**Firefly III Server Version:**
4.7.9
**Firefly III Mobile Version:**

1.1.2 via f droid

**Android Version:**  

9

**Device Information:**  

Pixel 2

--------------------------------------

## Expected Behavior

Correct oauth login

## Current Behavior

When attempting to log-in via oauth I am redirected back from chrome to the app and get the error
"CLEARTEXT communication to {MY-FIREFLY-IP} not permitted by network security policy"

## Steps to Reproduce

Input Oauth info in app then click sign in. After re-direction to chrome click Authorize. It then re-directs back to the app and produces the error.

![screenshot_20190111-000541](https://user-images.githubusercontent.com/4028391/51035154-163e8b80-1577-11e9-8ce7-734d84bdaf81.png)

**Comment by emansih** [comment]
I presume you are using http protocol?

**Comment by emansih** [comment]
Firefly III supports https out of the box. The reason you are seeing the above mentioned error is because Google has [disabled plaintext communication](https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted)(http) in all Android apps from Android 9 unless the developer(me) explicitly enables http protocol. I feel that you should not be using http protocol for any financial data anyway.

**Comment by 8bitgentleman** [comment]
I wasn't aware that firefly supported that. Could you maybe point me in the direction of an explanation of how to set it up? I didn't see one with a quick google search

**Comment by emansih** [comment]
https://gist.github.com/philthynz/ec04833a8e39c7f7d1b0d33cb4197a95#install-certbot-for-lets-encrypt
