### ISSUE TITLE
Add autocomplete for transaction descriptions

### ISSUE THREAD

**Issue by schneekluth** [emansih/FireflyMobile#85]
**Firefly III Server Version:**
5.0.5
**Firefly III Mobile Version:**
2.0.1
**Android Version:**  
10
**Device Information:**  

- BRAND: Oneplus
- MODEL: 7T
--------------------------------------

## Expected Behavior
When you start typing in the description field of a new transaction an autocomplete list should be displayed (like in firefly iii itself) based on transaction descriptions in the past. That way you could reduce errors for rules and bills getting linked to the transaction.
## Current Behavior
No autocomplete.

**Comment by emansih** [comment]
I would say this is a limitation in the API since currently there is no API for me to search for transactions for autocomplete to work. An expensive way to search for historical data is to download all transactions(which could be up to hundreds to tens of thousands of records) and do a query from there. There were plans to [add an API](https://github.com/firefly-iii/firefly-iii/issues/1730) though

**Comment by JC5** [comment]
It's not on my list yet but this can be added. I have plans to add a full search kind of a thing but auto-complete endpoints are not a bad idea. 

Keep track of https://github.com/firefly-iii/firefly-iii/issues/3150
